# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lpedit.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 581)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.qrcListGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.qrcListGroup.setObjectName("qrcListGroup")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.qrcListGroup)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qrcList = QtWidgets.QListWidget(self.qrcListGroup)
        self.qrcList.setObjectName("qrcList")
        self.horizontalLayout.addWidget(self.qrcList)
        self.horizontalLayout_2.addWidget(self.qrcListGroup)
        self.diffGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.diffGroup.setObjectName("diffGroup")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.diffGroup)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.qrcLayout = QtWidgets.QVBoxLayout()
        self.qrcLayout.setSpacing(0)
        self.qrcLayout.setContentsMargins(-1, 0, -1, -1)
        self.qrcLayout.setObjectName("qrcLayout")
        self.qrc_label_hlayout = QtWidgets.QHBoxLayout()
        self.qrc_label_hlayout.setSpacing(0)
        self.qrc_label_hlayout.setContentsMargins(0, -1, 8, -1)
        self.qrc_label_hlayout.setObjectName("qrc_label_hlayout")
        self.qrc_label = QtWidgets.QLabel(self.diffGroup)
        self.qrc_label.setObjectName("qrc_label")
        self.qrc_label_hlayout.addWidget(self.qrc_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.qrc_label_hlayout.addItem(spacerItem)
        self.timeTagCheckBox = QtWidgets.QCheckBox(self.diffGroup)
        self.timeTagCheckBox.setObjectName("timeTagCheckBox")
        self.qrc_label_hlayout.addWidget(self.timeTagCheckBox)
        self.qrcLayout.addLayout(self.qrc_label_hlayout)
        self.qrcLyric = QtWidgets.QListView(self.diffGroup)
        self.qrcLyric.setObjectName("qrcLyric")
        self.qrcLayout.addWidget(self.qrcLyric)
        self.horizontalLayout_3.addLayout(self.qrcLayout)
        self.lrcLayout = QtWidgets.QVBoxLayout()
        self.lrcLayout.setSpacing(4)
        self.lrcLayout.setContentsMargins(-1, 4, -1, -1)
        self.lrcLayout.setObjectName("lrcLayout")
        self.label_2 = QtWidgets.QLabel(self.diffGroup)
        self.label_2.setObjectName("label_2")
        self.lrcLayout.addWidget(self.label_2)
        self.standardLyric = QtWidgets.QListView(self.diffGroup)
        self.standardLyric.setObjectName("standardLyric")
        self.lrcLayout.addWidget(self.standardLyric)
        self.horizontalLayout_3.addLayout(self.lrcLayout)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_2.addWidget(self.diffGroup)
        self.buttonsVLayout = QtWidgets.QVBoxLayout()
        self.buttonsVLayout.setObjectName("buttonsVLayout")
        self.editButtonsGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.editButtonsGroup.setFlat(False)
        self.editButtonsGroup.setObjectName("editButtonsGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.editButtonsGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.saveThisButton = QtWidgets.QPushButton(self.editButtonsGroup)
        self.saveThisButton.setObjectName("saveThisButton")
        self.verticalLayout_2.addWidget(self.saveThisButton)
        self.saveAndNextButton = QtWidgets.QPushButton(self.editButtonsGroup)
        self.saveAndNextButton.setObjectName("saveAndNextButton")
        self.verticalLayout_2.addWidget(self.saveAndNextButton)
        self.skipButton = QtWidgets.QPushButton(self.editButtonsGroup)
        self.skipButton.setObjectName("skipButton")
        self.verticalLayout_2.addWidget(self.skipButton)
        self.dropThisButton = QtWidgets.QPushButton(self.editButtonsGroup)
        self.dropThisButton.setObjectName("dropThisButton")
        self.verticalLayout_2.addWidget(self.dropThisButton)
        self.reloadButton = QtWidgets.QPushButton(self.editButtonsGroup)
        self.reloadButton.setObjectName("reloadButton")
        self.verticalLayout_2.addWidget(self.reloadButton)
        self.buttonsVLayout.addWidget(self.editButtonsGroup)
        self.checkGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.checkGroup.setObjectName("checkGroup")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.checkGroup)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.getQrcManualyButton = QtWidgets.QPushButton(self.checkGroup)
        self.getQrcManualyButton.setObjectName("getQrcManualyButton")
        self.verticalLayout_3.addWidget(self.getQrcManualyButton)
        self.getLrcButton = QtWidgets.QPushButton(self.checkGroup)
        self.getLrcButton.setObjectName("getLrcButton")
        self.verticalLayout_3.addWidget(self.getLrcButton)
        self.playButton = QtWidgets.QPushButton(self.checkGroup)
        self.playButton.setObjectName("playButton")
        self.verticalLayout_3.addWidget(self.playButton)
        self.label_song_info = QtWidgets.QLabel(self.checkGroup)
        self.label_song_info.setObjectName("label_song_info")
        self.verticalLayout_3.addWidget(self.label_song_info)
        self.songInfoText = QtWidgets.QTextEdit(self.checkGroup)
        self.songInfoText.setReadOnly(True)
        self.songInfoText.setAcceptRichText(True)
        self.songInfoText.setObjectName("songInfoText")
        self.verticalLayout_3.addWidget(self.songInfoText)
        self.buttonsVLayout.addWidget(self.checkGroup)
        self.buttonsVLayout.setStretch(0, 1)
        self.buttonsVLayout.setStretch(1, 2)
        self.horizontalLayout_2.addLayout(self.buttonsVLayout)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 8)
        self.horizontalLayout_2.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 21))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_E = QtWidgets.QMenu(self.menubar)
        self.menu_E.setEnabled(True)
        self.menu_E.setObjectName("menu_E")
        self.menu_H = QtWidgets.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar1 = QtWidgets.QToolBar(MainWindow)
        self.toolBar1.setObjectName("toolBar1")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar1)
        self.toolBar2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar2.setEnabled(True)
        self.toolBar2.setObjectName("toolBar2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar2)
        self.toolBar3 = QtWidgets.QToolBar(MainWindow)
        self.toolBar3.setObjectName("toolBar3")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar3)
        self.openAction = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openAction.setIcon(icon)
        self.openAction.setObjectName("openAction")
        self.saveAction = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveAction.setIcon(icon1)
        self.saveAction.setObjectName("saveAction")
        self.quitAction = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitAction.setIcon(icon2)
        self.quitAction.setObjectName("quitAction")
        self.undoAction = QtWidgets.QAction(MainWindow)
        self.undoAction.setEnabled(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoAction.setIcon(icon3)
        self.undoAction.setObjectName("undoAction")
        self.redoAction = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redoAction.setIcon(icon4)
        self.redoAction.setObjectName("redoAction")
        self.aboutAction = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutAction.setIcon(icon5)
        self.aboutAction.setObjectName("aboutAction")
        self.newAction = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newAction.setIcon(icon6)
        self.newAction.setObjectName("newAction")
        self.copyAction = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copyAction.setIcon(icon7)
        self.copyAction.setObjectName("copyAction")
        self.pasteAction = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pasteAction.setIcon(icon8)
        self.pasteAction.setObjectName("pasteAction")
        self.dropAction = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dropAction.setIcon(icon9)
        self.dropAction.setObjectName("dropAction")
        self.skipAction = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/skip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skipAction.setIcon(icon10)
        self.skipAction.setObjectName("skipAction")
        self.previousAction = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousAction.setIcon(icon11)
        self.previousAction.setObjectName("previousAction")
        self.nextAction = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextAction.setIcon(icon12)
        self.nextAction.setObjectName("nextAction")
        self.stettingsAction = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icon/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stettingsAction.setIcon(icon13)
        self.stettingsAction.setObjectName("stettingsAction")
        self.shrtcutsAction = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icon/shortcuts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shrtcutsAction.setIcon(icon14)
        self.shrtcutsAction.setObjectName("shrtcutsAction")
        self.saveThisAction = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icon/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveThisAction.setIcon(icon15)
        self.saveThisAction.setObjectName("saveThisAction")
        self.reloadAction = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icon/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadAction.setIcon(icon16)
        self.reloadAction.setObjectName("reloadAction")
        self.getQrcAction = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icon/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.getQrcAction.setIcon(icon17)
        self.getQrcAction.setObjectName("getQrcAction")
        self.getLrcAction = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icon/text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.getLrcAction.setIcon(icon18)
        self.getLrcAction.setObjectName("getLrcAction")
        self.playAction = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icon/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playAction.setIcon(icon19)
        self.playAction.setObjectName("playAction")
        self.pauseAction = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icon/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseAction.setIcon(icon20)
        self.pauseAction.setObjectName("pauseAction")
        self.stopAction = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icon/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopAction.setIcon(icon21)
        self.stopAction.setObjectName("stopAction")
        self.closeProjeAction = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icon/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeProjeAction.setIcon(icon22)
        self.closeProjeAction.setObjectName("closeProjeAction")
        self.menu_F.addAction(self.openAction)
        self.menu_F.addAction(self.newAction)
        self.menu_F.addAction(self.saveAction)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.closeProjeAction)
        self.menu_F.addAction(self.quitAction)
        self.menu_E.addAction(self.undoAction)
        self.menu_E.addAction(self.redoAction)
        self.menu_E.addSeparator()
        self.menu_E.addAction(self.copyAction)
        self.menu_E.addAction(self.pasteAction)
        self.menu_E.addSeparator()
        self.menu_E.addAction(self.reloadAction)
        self.menu_E.addAction(self.dropAction)
        self.menu_E.addAction(self.skipAction)
        self.menu_E.addSeparator()
        self.menu_E.addAction(self.stettingsAction)
        self.menu_H.addAction(self.shrtcutsAction)
        self.menu_H.addAction(self.aboutAction)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_E.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())
        self.toolBar1.addAction(self.newAction)
        self.toolBar1.addAction(self.openAction)
        self.toolBar1.addAction(self.saveAction)
        self.toolBar2.addAction(self.copyAction)
        self.toolBar2.addAction(self.pasteAction)
        self.toolBar2.addAction(self.undoAction)
        self.toolBar2.addAction(self.redoAction)
        self.toolBar2.addSeparator()
        self.toolBar2.addAction(self.saveThisAction)
        self.toolBar2.addAction(self.dropAction)
        self.toolBar2.addAction(self.skipAction)
        self.toolBar2.addAction(self.previousAction)
        self.toolBar2.addAction(self.nextAction)
        self.toolBar2.addAction(self.reloadAction)
        self.toolBar2.addSeparator()
        self.toolBar2.addAction(self.getQrcAction)
        self.toolBar2.addAction(self.getLrcAction)
        self.toolBar2.addSeparator()
        self.toolBar2.addAction(self.playAction)
        self.toolBar2.addAction(self.pauseAction)
        self.toolBar2.addAction(self.stopAction)
        self.toolBar3.addAction(self.shrtcutsAction)
        self.toolBar3.addAction(self.stettingsAction)
        self.qrc_label.setBuddy(self.qrcLyric)
        self.label_2.setBuddy(self.standardLyric)
        self.label_song_info.setBuddy(self.songInfoText)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.qrcListGroup.setTitle(_translate("MainWindow", "QRC列表"))
        self.diffGroup.setTitle(_translate("MainWindow", "歌词对比"))
        self.qrc_label.setText(_translate("MainWindow", "QRC:"))
        self.timeTagCheckBox.setText(_translate("MainWindow", "显示时间标签"))
        self.label_2.setText(_translate("MainWindow", "标准歌词："))
        self.editButtonsGroup.setTitle(_translate("MainWindow", "编辑"))
        self.saveThisButton.setText(_translate("MainWindow", "保存本首"))
        self.saveAndNextButton.setText(_translate("MainWindow", "保存并编辑下一首"))
        self.skipButton.setText(_translate("MainWindow", "放弃修改跳过本首"))
        self.dropThisButton.setText(_translate("MainWindow", "丢弃本首"))
        self.reloadButton.setText(_translate("MainWindow", "重新载入歌词"))
        self.checkGroup.setTitle(_translate("MainWindow", "校验"))
        self.getQrcManualyButton.setText(_translate("MainWindow", "手动获取QRC"))
        self.getLrcButton.setText(_translate("MainWindow", "重新获取标准歌词"))
        self.playButton.setText(_translate("MainWindow", "播放本曲"))
        self.label_song_info.setText(_translate("MainWindow", "歌曲信息:"))
        self.menu_F.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu_E.setTitle(_translate("MainWindow", "编辑(&E)"))
        self.menu_H.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.toolBar1.setWindowTitle(_translate("MainWindow", "toolBar1"))
        self.toolBar2.setWindowTitle(_translate("MainWindow", "toolBar2"))
        self.toolBar3.setWindowTitle(_translate("MainWindow", "toolBar3"))
        self.openAction.setText(_translate("MainWindow", "打开"))
        self.openAction.setToolTip(_translate("MainWindow", "打开qrc列表"))
        self.openAction.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.saveAction.setText(_translate("MainWindow", "保存"))
        self.saveAction.setToolTip(_translate("MainWindow", "保存"))
        self.saveAction.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.quitAction.setText(_translate("MainWindow", "退出"))
        self.quitAction.setToolTip(_translate("MainWindow", "退出程序"))
        self.undoAction.setText(_translate("MainWindow", "撤销"))
        self.undoAction.setToolTip(_translate("MainWindow", "撤销操作"))
        self.undoAction.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.redoAction.setText(_translate("MainWindow", "重做"))
        self.redoAction.setToolTip(_translate("MainWindow", "重做"))
        self.redoAction.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.aboutAction.setText(_translate("MainWindow", "关于..."))
        self.aboutAction.setToolTip(_translate("MainWindow", "关于lpEdit"))
        self.newAction.setText(_translate("MainWindow", "新建"))
        self.newAction.setToolTip(_translate("MainWindow", "新建工程"))
        self.newAction.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.copyAction.setText(_translate("MainWindow", "复制"))
        self.copyAction.setToolTip(_translate("MainWindow", "复制"))
        self.copyAction.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pasteAction.setText(_translate("MainWindow", "粘贴"))
        self.pasteAction.setToolTip(_translate("MainWindow", "粘贴"))
        self.pasteAction.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.dropAction.setText(_translate("MainWindow", "丢弃本首"))
        self.dropAction.setToolTip(_translate("MainWindow", "删除本首"))
        self.skipAction.setText(_translate("MainWindow", "跳过本首"))
        self.skipAction.setToolTip(_translate("MainWindow", "放弃修改并跳过本首"))
        self.skipAction.setShortcut(_translate("MainWindow", "Ctrl+Down"))
        self.previousAction.setText(_translate("MainWindow", "上一首"))
        self.previousAction.setToolTip(_translate("MainWindow", "编辑上一首"))
        self.previousAction.setShortcut(_translate("MainWindow", "Ctrl+Left"))
        self.nextAction.setText(_translate("MainWindow", "下一首"))
        self.nextAction.setToolTip(_translate("MainWindow", "编辑下一首"))
        self.nextAction.setShortcut(_translate("MainWindow", "Ctrl+Right"))
        self.stettingsAction.setText(_translate("MainWindow", "设置"))
        self.stettingsAction.setToolTip(_translate("MainWindow", "设置"))
        self.shrtcutsAction.setText(_translate("MainWindow", "快捷键"))
        self.shrtcutsAction.setToolTip(_translate("MainWindow", "查看快捷键"))
        self.saveThisAction.setText(_translate("MainWindow", "保存本首"))
        self.saveThisAction.setToolTip(_translate("MainWindow", "保存本首"))
        self.saveThisAction.setShortcut(_translate("MainWindow", "F5"))
        self.reloadAction.setText(_translate("MainWindow", "重新载入"))
        self.reloadAction.setToolTip(_translate("MainWindow", "重新载入本首QRC(放弃更改)"))
        self.reloadAction.setShortcut(_translate("MainWindow", "F4"))
        self.getQrcAction.setText(_translate("MainWindow", "手动获取QRC"))
        self.getQrcAction.setToolTip(_translate("MainWindow", "手动重新获取QRC，更精确"))
        self.getQrcAction.setShortcut(_translate("MainWindow", "F7"))
        self.getLrcAction.setText(_translate("MainWindow", "获取标准歌词"))
        self.getLrcAction.setToolTip(_translate("MainWindow", "选择从qq音乐或者lyricWiki获取歌词"))
        self.playAction.setText(_translate("MainWindow", "播放本曲"))
        self.playAction.setToolTip(_translate("MainWindow", "播放本首(从qq音乐)"))
        self.playAction.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.pauseAction.setText(_translate("MainWindow", "暂停播放"))
        self.pauseAction.setToolTip(_translate("MainWindow", "暂停播放"))
        self.stopAction.setText(_translate("MainWindow", "停止播放"))
        self.closeProjeAction.setText(_translate("MainWindow", "关闭工程"))
        self.closeProjeAction.setToolTip(_translate("MainWindow", "关闭本工程"))
        self.closeProjeAction.setShortcut(_translate("MainWindow", "Ctrl+F4"))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

